language: perl
perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
before_install:
  - cpanm -n DBD::SQLite Devel::Cover::Report::Coveralls
script:
  - perl Build.PL && ./Build build && cover -test
after_success:
  - cover -report coveralls
